version: "3.4"

services:
  app:
    build:
      context: ./
      dockerfile: .devcontainer/Dockerfile
      args:
        UID: 1000
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
       - ./:/var/www/html
    #  - ./:/workspace
    #  - /var/run/docker.sock:/var/run/docker.sock
    #command: /bin/sh -c "service apache2 start && while sleep 1000; do :; done"