version: "3.4"

services:
  app:
    build:
      context: ./
      dockerfile: .devcontainer/Dockerfile
      args:
        UID: 1001
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - APACHE_RUN_USER=#1001
      - APACHE_RUN_GROUP=#1001