version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: 1001
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock
    command: /bin/sh -c "service apache2 start && while sleep 1000; do :; done"
    environment:
      - APACHE_RUN_USER=#1001
      - APACHE_RUN_GROUP=#1001